version: "2.1"
orbs:
  python: circleci/python@2.1.1
  heroku: circleci/heroku@2.0

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.8-node
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: test_db
          POSTGRES_PASSWORD: circleci_pass
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
    steps:
      - checkout
      - run:
          name: Wait for PostgreSQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0;
              echo "Waiting for PostgreSQL to start...";
              sleep 1;
            done;
            echo "Failed to connect to PostgreSQL" && exit 1;
      - run: 
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install django 
      - run:
          name: Verify installation and activation
          command: |
            . venv/bin/activate
            which python
            python3 -m pip show django 
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            export DJANGO_SECRET_KEY='oi3bieche)boo7ienie7Ba4nA[cHeepoonilahchuOgh3kohn{ei3hoo9bAi7uosiey<u$ocAz}ah7shic7xAi7aicEith4chu!e'
            export POSTGRES_DB=test_db
            export POSTGRES_USER=circleci
            export POSTGRES_PASSWORD=circleci_pass
            export POSTGRES_HOST=localhost
            export POSTGRES_PORT=5432
            python manage.py test
  
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: 
                - main