version: "2.1"
orbs:
  python: circleci/python@2.1.1
  heroku: circleci/heroku@2.0
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.8-node
      - image: circleci/postgres:13.2
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: test_db
          POSTGRES_PASSWORD: circleci_pass
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
    environment:
      POSTGRES_USER: circleci
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: circleci_pass
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    steps:
      - checkout
      - run:
        name: Wait for PostgreSQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0;
              echo "Waiting for PostgreSQL to start...";
              sleep 1;
            done;
            echo "Failed to connect to PostgreSQL" && exit 1;
      - python/install-packages
      - run:
        name: Run tests
        command: python manage.py test
  
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: main