# Generated by Django 5.0.6 on 2024-05-29 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('mood', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
