# Generated by Django 5.0.6 on 2024-05-23 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='user',
        ),
        migrations.AddField(
            model_name='mood',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
