# Generated by Django 5.0.6 on 2024-05-23 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_api', '0002_remove_mood_user_mood_user_id_alter_mood_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
