# Generated by Django 5.0.6 on 2024-05-23 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_api', '0004_alter_mood_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
